### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by trebmuh** [mzuther/Squeezer#1]
_(or maybe a copy/paste error)_

Reading at the [README.markdown](https://github.com/mzuther/Squeezer/blob/master/README.markdown) text, it's mentioned that there is a .pdf documentation (similarly to kmeter and trakmeter), but there isn't such a file in the repo.

I'm writing this here then it doesn't get unnoticed, in the hope that helps.

**Comment by mzuther** [comment]
Thanks for the bug report! So far, Squeezer is just a (highly professional) playground for learning about and playing with compression. Thus, Squeezer has changed a lot over the years and I have never documented it. It's ready for release, but I haven't gotten around to actually do it.

For now, I have updated the README (yes, it was pure copy-and-paste).

But I'll leave this issue open as a reminder. :)

**Comment by mzuther** [comment]
The manual is finished and I will release Squeezer in the next few days. Thanks again! :smile:

**Comment by trebmuh** [comment]
Super nice @mzuther. I can't wait for the new release!

**Comment by mzuther** [comment]
I hurried up: https://github.com/mzuther/Squeezer/releases

**Comment by trebmuh** [comment]
Super fast! Thank you. I've packaged it for LibraZiK.

**Comment by mzuther** [comment]
Great, thanks! :smile:
