### ISSUE TITLE
Bug: VST3 on Cubase Does not save Settings 

### ISSUE THREAD

**Issue by BerlinSiege** [mzuther/Squeezer#11]
### Describe the bug
GREAT COMPRESSOR!!!! CONGRATS!!

Cubase 5 on Win 10
Vst3
Stereo squeezer version

### Steps to reproduce

List *all* steps to reproduce the behavior:

1. [ start Cubase 5 ]
2. [ Load  song ]
3. [ open the mixer ]
4. [ add squeezer ]
5. [ add *Squeezer Stereo, no side-chain* to the track's first plug-in slot ]
6. save preset
7. load preset 
8. No preset listed in select box

### Expected behavior
save preset should be visible

**Comment by mzuther** [comment]
Thanks for the bug report (and editing, it's now much clearer)!

I have already changed an internal setting because of this. Of course, this was immediately *after* I released Squeezer 2.5.4. :roll_eyes: 

Could you please test these files:

+ http://public.mzuther.de/squeezer-w64-vst2_2.5.5-issue-11.1.zip
+ http://public.mzuther.de/squeezer-w64-vst3_2.5.5-issue-11.1.zip

and tell me if preset saving now works? Thanks!

**Comment by BerlinSiege** [comment]
Hi There,
Sure, will do. 
Great comp!

**Comment by mzuther** [comment]
Thanks for the praise! :smile: 

In case you haven't downloaded yet, I have changed the download links:

+ [squeezer-w64-vst2_2.5.5-issue-11.1.zip](http://public.mzuther.de/?74009c96613f80ee6cc785dcd17d51759546996f)
+ [squeezer-w64-vst3_2.5.5-issue-11.1.zip](http://public.mzuther.de/?2f49c10ccecd397bec4fd377dae9a7c672ef70f7)

**Comment by BerlinSiege** [comment]
Thanks for the quick response !  I will test it today. 

Cheers

**Comment by mzuther** [comment]
Hi! 

Did you find the time to check whether my new version of Squeezer VST saves settings in Cubase?

**Comment by BerlinSiege** [comment]
Hi Mattin, 
I got sidetracked by a client project 
since we last chatted. 

I have time to do so today or tomorrow. 


Best,


Andy

**Comment by mzuther** [comment]
I'm currently working on Squeezer and hope to release a new version soon. Could you please check whether my new version of Squeezer VST saves settings in Cubase? I don't want to release Squeezer with this bug lurking around. Thanks!

**Comment by BerlinSiege** [comment]
Yes,
I can!

Best Regards, 


Andy Vasen
503.881.9115

**Comment by BerlinSiege** [comment]
Hi Martin,
Do you have a new version I could test?

Best Regards, 


Andy Vasen
503.881.9115

**Comment by mzuther** [comment]
I have just moved, so my home is in pieces... But you can test the version I linked above, the changes to Squeezer I have made since are purely cosmetical!

**Comment by BerlinSiege** [comment]
Hi -  no link :))

Best Regards, 


Andy Vasen
503.881.9115

**Comment by mzuther** [comment]
They were in an old post further up... :smile:

+ [squeezer-w64-vst2_2.5.5-issue-11.1.zip](http://public.mzuther.de/?74009c96613f80ee6cc785dcd17d51759546996f)
+ [squeezer-w64-vst3_2.5.5-issue-11.1.zip](http://public.mzuther.de/?2f49c10ccecd397bec4fd377dae9a7c672ef70f7)

**Comment by BerlinSiege** [comment]
Hi Martin,
Have you ever dabbled with transformer emulations?

It is a big part of the 3D effect of tube compressors. 

Best Regards, 


Andy

**Comment by mzuther** [comment]
You asked for it:

+ [squeezer-w64-vst2_v2.5.4-136-gec17d76f.zip](https://public.mzuther.de/?48cd245b79b20c21ea661889cf6335b63c880ff1)
+ [squeezer-w64-vst3_v2.5.4-136-gec17d76f.zip](https://public.mzuther.de/?b273a76f57cc477a5bfc389402ddc0373b633620)

You can also test screen scaling by clicking on the "Skin" button...

**Comment by mzuther** [comment]
Most of my recordings go through a transformer, so I have not dabbled with transformer emulations yet. But I wouldn't mind doing so. Have you got any ideas where to start?

However, I'll first add over-sampling. That should add a bit of "3D", too. :smile:

**Comment by mzuther** [comment]
I'm closing this issue because I haven't received any response to my beta versions. The download links will remain active for a couple of days, though, and you can still post here.
