### ISSUE TITLE
Bug: No GUI appears (Windows, 64-bit, VST3, Cubase 10.5, Intel HD Graphics 2000 chip)

### ISSUE THREAD

**Issue by IsaakCode** [mzuther/Squeezer#13]
### Describe the bug

No GUI

### Steps to reproduce

Start Cubase, load the plugin on an FX inserf

### Expected behavior

The plugin with it's GUI will appear

### Environment (please complete the following information)

 - OS: Windows 7 64-bit
 - DAW: Cubase 10.5 (64-bit)
 - Plug-in: Squeezer v2.5.4 VST2  & VST3 (64-bit)

Did you compile Squeezer yourself? [no]

### Additional context

The computer is using an Intel Graphics HD 2000 graphics unit!

--

**Comment by mzuther** [comment]
Thanks for your bug report!

I cannot reproduce your problem, as I don't own Cubase.  However, did you copy the `squeezer` folder to the folder where you placed the plug-in DLLs? This is a common problem and I'm working on it (but it's going slow).

Martin

**Comment by mzuther** [comment]
Closed because of inactivity.
