### ISSUE TITLE
Bug: No GUI (Win x64, VST3, Reaper 6.15, Intel Iris Plus Graphics 655)

### ISSUE THREAD

**Issue by zombiebub** [mzuther/Squeezer#14]
### Describe the bug

The plug-in loads but the GUI doesn't appear

### Steps to reproduce

1. [ start Reaper ]
2. [ create a new project ]
3. [ add a track ]
4. [ add *Squeezer Stereo* or *Squeezer Mono* to the track's FX chain ]
5. [ see error ... ]

### Expected behavior

The GUI should appear

### Environment (please complete the following information)

 - OS: [ Windows 10 (64-bit) ]
 - DAW: [ Reaper v6.15 (64-bit) ]
 - Plug-in: [ Squeezer v2.5.4 VST3 (64-bit) ]

Did you compile Squeezer yourself? [no]

### Additional context

Tested with VST-host Blue Cat Patchwork 2 and the same problem occurs.

Vcredist 2015, 2017 and 2019 x64 is installed

**Comment by mzuther** [comment]
Thanks for your bug report!

I cannot reproduce your problem, though -- on my system, both the VST2 and VST3 plug-ins run just fine in Reaper 6.15.

Did you copy the `squeezer` folder to the folder where you placed the plug-in DLLs?

Martin

**Comment by zombiebub** [comment]
Hi!

I'm so stupid.

I first copied the contents of the .rar to my VST3 folder and then for some
reason I moved the DLLs into the squeezer folder.

Guess I was trying to keep things tidy or something.

It works just fine now!

Thanks for replying!

/Jon

Den mån 16 nov. 2020 kl 23:09 skrev Martin Zuther <notifications@github.com

**Comment by mzuther** [comment]
Great that it works! You're more than welcome. :)

And you're not stupid – the "squeezer" folder is quite a problem and I'm working to get rid of it...
