### ISSUE TITLE
Feature request: Skin with custom knobs and value readouts

### ISSUE THREAD

**Issue by CsHajdu** [mzuther/Squeezer#16]
I made a skin for Squeezer, but it turned out a bit too complicated for me to apply it.

I wondered if it would be possible to somehow make it happen - it has a bunch of things I have no idea how to make work. Custom knobs, the buttons that disable the stepped values are awkwardly shaped,.. I could make out the button states and positioning, the background image and the meter as well (except the spacing between the rectangles), but the rest is not so clear in the xml structure (maybe not even available). 

I have next to no experience with GUI design, but I think this turned out pretty neat and I wouldn't want it to go to waste. I can prepare the assets and provide the Inkscape project as well.

![squeezer_skin](https://user-images.githubusercontent.com/83515435/116809431-4a6e5980-ab3e-11eb-9db1-917d3545b4c0.png)

**Comment by mzuther** [comment]
Hey @CsHajdu, this looks great! :smile: I'm sorry for keeping you waiting...

Unfortunately, I have already removed all skin-related code in the development version. Also, my time has been quite limited for some time. So for the time being, I cannot implement this.

However, please keep the files! Sometimes I find a bit of spare time or have an idea how to easily implement a new feature.

Thanks again, you really made my day! :smile:

**Comment by CsHajdu** [comment]
Hey Martin!

Glad to hear from you. I will keep things for future use, but if you're open to it this could be "outsourced", maybe someone is interested in making it happen (i.e. in the KVR developer forums). That would also promote this sweet piece of code you wrote.

Think about it. And thanks for making this compressor. it is great! 

Oh, and I redid the knobs and did a general cleanup a while back, so currently it looks like this:

![squeezer_skin](https://user-images.githubusercontent.com/83515435/125670658-49c07f91-8677-48ef-ac31-d86f3468e7b7.png)

**Comment by mzuther** [comment]
Dammit, this looks even better! :smile: 

I'm not averse to "outsorcing" at all, it's simply a problem of lacking spare time on my side. And there are other issues that need to be fixed before this as well. But maybe an opportunity will arise...

**Comment by oguma** [comment]
I like Squeezer so much. It's unique and all-round. Only reason I hesitate to insert to my tracks is color of GUI. It's too vivid and hard for my eyes. Good for my ears, but not so good for my eyes... So, consider soften color GUI, please. I appreciate your effort. Thanks.

**Comment by mzuther** [comment]
@oguma Thanks for the praise and input. I'm very busy and have no time for this, but if you (or @CsHajdu) want to play around with the **colors** (not the layout!) of Squeezer and suggest a nicer version, feel free to download this file: https://github.com/mzuther/Squeezer/blob/develop/skins/Original/Skin.svg (open the file with Inkscape 1.x) and edit it.

This would be easy to adjust for me, whereas moving to the new skin needs a lot of time that I currently do not have. I cannot promise anything, but hey, it's worth a try! :smile:
