### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by kmturley** [mzuther/Squeezer#17]
Thankyou for creating a free plugin!

In your README file you mention code is released under GNU General Public License.

Could you add a LICENSE file to the repo to confirm this in code?
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Should take 5 minutes.

Thanks!

**Comment by mzuther** [comment]
Hi kmturley,

thanks for opening this issue! There is in fact a LICENSE file, but it's located in the `doc/` folder.

I have to admit that the README file was a bit vague in this regard, so I have updated it accordingly.

Best regards,

Martin

**Comment by kmturley** [comment]
Ah thanks for responding.

I didn't see it because it was inside the docs folder.

GitHub only parse the license if it is at the root of the repo. See comparison of your repo vs Surge
<img width="319" alt="Screen Shot 2022-03-01 at 12 52 54 PM" src="https://user-images.githubusercontent.com/1710493/156247189-322113c8-714b-4e81-a99c-baa0eeddc107.png">
<img width="318" alt="Screen Shot 2022-03-01 at 12 53 51 PM" src="https://user-images.githubusercontent.com/1710493/156247201-3a1e28af-7ca2-46a2-a121-652f31855101.png">
