### ISSUE TITLE
attempt to call a nil value

### ISSUE THREAD

**Issue by magnetophon** [mzuther/Squeezer#3]
When I try to build on NixOS, I get the following output:
```
=== Generating premake script ===
Rendering file 'premake5.lua'...
Done.

=== Generating project files (Visual C++, Windows) ===

Error: ...ix-build-squeezer-2.5.3.drv-0/source/Builds/premake5.lua:184: attempt to call a nil value (global 'omitframepointer')


=== Generating project files (Visual C++, Windows) ===

Error: ...ix-build-squeezer-2.5.3.drv-0/source/Builds/premake5.lua:184: attempt to call a nil value (global 'omitframepointer')


=== Generating project files (Clang++, LINUX) ===

Error: ...ix-build-squeezer-2.5.3.drv-0/source/Builds/premake5.lua:184: attempt to call a nil value (global 'omitframepointer')
```

**Comment by mzuther** [comment]
I need much more information (version numbers, premake5.lua after rendering etc.) to help you with this (if I can at all).

Most importantly, are you using premake 5.0.0 (alpha14)?

**Comment by magnetophon** [comment]
I was using alpha12.
Trying to build alpha14 atm.

**Comment by mzuther** [comment]
Hi Bart,

I am currently occupied with bug reports and improvements to my plug-ins, so I cannot help you unless you

* first check with the manual that you have at least the required versions for each tool
* report the version of each tool
* report your system version and "bit-ness"
* describe *exactly* what you were doing

Everything compiles fine (64 bit on current Linux Mint) with either clang version 6.0.0 and g++ 7.5.0.

Martin

**Comment by mzuther** [comment]
I have just updated the issue tracker. If you create a *new* issue, it will ask you for most information that I need.  So maybe it's easiest if you create a new issue and we'll close this one...

**Comment by magnetophon** [comment]
Hi Martin.
Thanks, I created a new issue with more details: https://github.com/mzuther/Squeezer/issues/6
