### ISSUE TITLE
Squeezer 2.5.3 - Linux VST2 plug-in : Ardour crash

### ISSUE THREAD

**Issue by Berhu3** [mzuther/Squeezer#4]
Hi,

I've put VST2 plug-in version of squeezer into this one : /usr/lib/vst
I've launch Ardour, add squeezer on a track : Ardour (5.12.0) crash immediately...

**Comment by mzuther** [comment]
Hi Berhu3,

thanks for your report!  I have checked Squeezer and it loads just fine in MixBus 32C 6.0.0 (which is based on Ardour).

I have just updated the issue tracker.  If you create a new issue, it will automatically ask for all the information I need.  So could you please create a *new* issue?  This would be easiest for both of us.

Thanks!

Martin

**Comment by mzuther** [comment]
Moved to #5.  Thanks! :smile:
