### ISSUE TITLE
Bug: Squeezer 2.5.3 - Linux VST2 plug-in : Ardour crash

### ISSUE THREAD

**Issue by Berhu3** [mzuther/Squeezer#5]
### Describe the bug

A *clear and concise* description of what the bug is.

I've launch Ardour, add squeezer on a track : Ardour (5.12.0) crash immediately...

### Steps to reproduce

1. I've download squeezer-linux64-vst2_2.5.3.tar.gz (uncompressed it)
2. Using root account, i've copy squeezer-linux64-vst2_2.5.3 folder into /usr/lib/vst directory
3. Launch Ardour 5.12.0
4. Open an existing song
5. On an existing stereo track, choose : add plug-in by creator
6. add *Squeezer Stereo, no side-chain* to the track's first plug-in slot
7. After choosing it : no error message, ardour crash immediately

### Environment (please complete the following information)

 - OS: Linux Mint 19.3
 - DAW: Ardour v5.12.0
 - Plug-in: Squeezer v2.5.3 VST2 (64-bit)

Did you compile Squeezer yourself? No

**Comment by mzuther** [comment]
Thanks for updating the issue and providing more information! :smile: 

Please follow these steps in the order I list them:

1. Did you copy the folder `squeezer` to `/usr/lib/vst`?  If not, please do so and see if it changes anything.

2. I have just released version 2.5.4.  Please install it exactly the way you installed 2.5.3.  I have an idea that it won't work, but as I've changed a few things, it's worth a try.

3. I think your problem might be related to copying the plug-in (and especially the folder `squeezer`) using `root`.  On Linux, this should always be a last resort, and there is almost always an easier way.  `~/.vst` is (almost) a standard directory, and you can set [environment variables](https://wiki.archlinux.org/index.php/Professional_audio#Environment_variables), but I think Ardour ignores both solutions.  So start Ardour *from the console*, open *Edit -> Preferences -> Plugins -> VST* and click on *Linux VST Path -> Edit*.  Then just add `~/.vst` (or wherever you copied the plug-in). You might have to force a plug-in reload, too.  Does it work now?

4. If Ardour crashed, can you copy its output on the console? It might be helpful.

Good luck!

Martin

P.S.: I have now tried on of the VST2 plugins on Ardour 5.12.0 (Linux Mint 19.3) and it didn't crash.  I cannot wrap my head around Ardour and really recommend Mixbus which is much easier to understand...

**Comment by Berhu3** [comment]
1. and 2. : Same issue with 2.5.4
3. You're right ! root access as the trouble ! I look into ardour, my default vst path was : 
/home/*myuser*/.vst
I've copy squeezer folder into it and now it works !

Thanks a lot for your help !

Maybe i'll buy Mixbus ! Thanks for the advice !

**Comment by mzuther** [comment]
You're welcome. I had already fixed this problem, but it seems that there still was a gap left to fill. So thanks for your input!

From the next release on, this is hopefully fixed for good...
