### ISSUE TITLE
Bug: no GUI in Cubase

### ISSUE THREAD

**Issue by IsaakCode** [mzuther/Squeezer#8]
### Describe the bug

When inserting the plugin in Cubase (Windows 7) the GUI does not appear. 

### Environment (please complete the following information)

 - OS: Windows 7 (64-bit)
 - DAW: Cubase 10 (64-bit version)
 - Plug-in: [ Squeezer v2.5.3 VST3 (64-bit)

**Comment by mzuther** [comment]
Please open a new bug report and answer **all questions**. Thank you!

**Comment by IsaakCode** [comment]
What specific information are you missing?

**Comment by mzuther** [comment]
Sorry, I was a bit in a hurry when I wrote that. When you open a bug report, there are several questions that help me in helping you.

As you seem to have deleted most of them, opening a new issue is the easiest way to get a full set of questions. Currently, your bug report does not contain enough information, so I can either ignore it (which I don't want to) or I have to play detective (thus spending time that is better spent in improving Squeezer).
