### ISSUE TITLE
Bug: Stereo version only outputs left channel audio in Bitwig Studio 3.1.3 Linux

### ISSUE THREAD

**Issue by metasequence** [mzuther/Squeezer#9]
### Describe the bug

The Stereo version only outputs left channel audio in Bitwig Studio 3.1 on Linux. No right channel audio is shown volume meter in the plugin or Bitwig's mixer. The "Bypass" button in Squeezer has no effect.

If I add an external sidechain then the sidechain audio is output on the right channel.

The Mono version works as expected.

### Steps to reproduce

List *all* steps to reproduce the behavior:

1. start Bitwig 
2. create a new song
3. add an instrument (ie. FM-4)
4. add Squeezer Stereo after FM-4
5. play some notes on FM-4

### Expected behavior

Audio plays out of both channels.

### Environment (please complete the following information)

 - OS: [ Ubuntu 20.04 x64 ]
 - DAW: [ Bitwig 3.1.3 ]
 - Plug-in: [ Squeezer v2.5.4 (VST2) Linux 64-bit - squeezer_stereo_vst2_x64.so ]

Are Squeezer and the directory "squeezer" located in the folder? [yes]
Did you compile Squeezer yourself? [no]

### Additional context

Thank you!

**Comment by mzuther** [comment]
Thanks for your bug report!  I do not have access to Bitwig, but maybe we can still figure it out...

This might be a routing issue. Could you please try the plug-in `squeezer_stereo_no_sidechain_vst2_x64.so` and report wether it works? I created it because there was a similar problem with FL Studio.

**Comment by mzuther** [comment]
As this could be a issue for quite a few users, I have just created a [FAQ](https://github.com/mzuther/Squeezer/wiki) on the Wiki. :smile:

**Comment by metasequence** [comment]
Yes, that one works great, thank you!

If there is any way I can assist you in debugging this so there could be a Stereo Sidechain version that works in Bitwig/FL Studio/etc. please let me know. That function is very useful.

From what I can gather it looks like the audio inputs and sidechain inputs are getting swapped between Bitwig and Squeezer. When I add the external sidechain I can hear the compressor audio normally in left channel and then the sidechain appears in the right audio. 

Thank you for your hard work on this great project and for your assistance!

**Comment by mzuther** [comment]
Great - you're welcome!

And thanks for the offer, that's very kind of you. But I won't change the channels in VST2 - here is why (from the new FAQ): "VST2 does not support side-chains. I have found a way around this limitation, but unfortunately some hosts will behave erratically." So whatever I change to make it work in Bitwig will break it on other hosts.

Does Bitwig support VST3 plug-ins on Linux? In that case, I could release a VST3 plug-in for Linux (VST3 supports side-chaining). And you could be the ~scapegoat~ debugging pioneer... :grin:

**Comment by metasequence** [comment]
Yes, Bitwig does support VST3. That would be an ideal solution! I'm happy to be your guinea pig on this one :)

**Comment by mzuther** [comment]
Oh no! I mean, great, thanks! :wink: 

I will now close this issue, could you please subscribe to issue #10 (the easiest way is probably a short comment)? The new issue helps me in keeping my focus.
